# base URL
server:
  port: 8081
  servlet:
    context-path: /news
    multipart:
      max-file-size: 20M
      max-request-size: 20M
    session:
      timeout: 2000s

# spring
spring:
  resources:
    static-locations: classpath:/static/
  # Mysql data source
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newsdb?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  dubbo:
    application:  #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: consumer
    registry:     #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受（订阅）。
      name: dubbo
      port: 20880
    consumer:
      check: false
    reference:
      loadbalance: roundrobin #轮询机制
      #loadbalance: random #随机机制
      #loadbalance: leastactive #最少活跃调用数机制
  redis:
    host: 127.0.0.1
    jedis:
      pool:
        # 连接池中的最大连接数
        max-idle: 10
        # 连接池中的最大阻塞等待时间
        max-wait: -1ms
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 100ms
    # Redis服务器连接密码（默认为空）
    password: 135246
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 300ms
    session:
      store-type: redis
      redis:
        flush-mode: on_save
        namespace: spring:session


#user:
#  school: tongji
