# base URL
server:
  port: 8088
  servlet:
    context-path: /mind
    multipart:
      max-file-size: 20M
      max-request-size: 20M

# spring
spring:
  resources:
    static-locations: classpath:/static/
  # Mysql data source
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newsdb?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# config
config:
  file:
    sources: ../../News_Classification/classification/
    target: /data/shgx/Picasso/News_Classification/classification/
  target:
    keyfile: ~/.ssh/news
    user: shgx
    host: 10.60.103.246
    port: 21122
    password: shgx
